[2025-07-05 11:06:40,442] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-05 11:06:40,450] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-05 11:06:40,452] INFO _log() L97    * Restarting with stat - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-05 11:06:43,623] WARNING _log() L97    * Debugger is active! - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-05 11:06:43,624] INFO _log() L97    * Debugger PIN: 167-900-395 - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-05 11:07:11,144] INFO _log() L97   127.0.0.1 - - [05/Jul/2025 11:07:11] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-05 11:12:01,858] INFO _log() L97   127.0.0.1 - - [05/Jul/2025 11:12:01] "GET /list-iris HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-05 11:12:26,375] WARNING predict() L117  Erro ao adicionar iris, Iris já existente na base de dados. - call_trace=c:\projetos\pós-graduação\sprint-02\mvp\ML4Iris\api\app.py L117 
[2025-07-05 11:12:26,378] INFO _log() L97   127.0.0.1 - - [05/Jul/2025 11:12:26] "[31m[1mPOST /iris HTTP/1.1[0m" 409 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-05 11:16:59,512] INFO _log() L97   127.0.0.1 - - [05/Jul/2025 11:16:59] "GET /list-iris HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L97  
